title : Todd Garon
tagline: A personal Website
name : Todd Garon
email : toddgaron@gmail.com
github : toddgaron
instagram : usergeneratedcontent
baseurl: ""
url: "https://www.toddgaron.com"
permalink: /404.html
